stages:
  - build
  - run

.yarn_build:
  image: node:10
  script: |
    yarn install  # Install all dependencies
    yarn build    # Build command
  artifacts:
    paths:
      - ./build

yarn_dev:
  extends: .yarn_build
  stage: build
  only:
    refs:
      - staging

yarn_prod:
  extends: .yarn_build
  stage: build
  only:
    refs:
      - master

.deploy_aws:
  image: python:latest
  script: |
    pip install awscli #Install awscli tools
    aws s3 sync ./build/ s3://${S3_BUCKET}

deploy_dev:
  extends: .deploy_aws
  stage: run
  dependencies:
    - yarn_dev
  before_script:
    - echo XXX $S3_BUCKET_STAGING XXX
    - export S3_BUCKET=$S3_BUCKET_STAGING
  only:
    refs:
      - staging

deploy_prod:
  extends: .deploy_aws
  stage: run
  dependencies:
    - yarn_prod
  before_script:
    - export S3_BUCKET=$S3_BUCKET_PROD
  only:
    refs:
      - master
