/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

/**
 * Autogenerated input type of UpdateGroupStatus
 */
export interface UpdateGroupStatusInput {
  groupId: string;
  status: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of UpdateUserStatus
 */
export interface UpdateUserStatusInput {
  userId: string;
  status: string;
  clientMutationId?: string | null;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
